---
title: "Introdução à Regresssão para Ciências Sociais"
author: "Manoel Galdino"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
lang: pt
---

# - Prefácio

Esse livro é, por enquanto, apenas uma repositório de notas de aula do curso de graduação da Ciências Sociais da USP, FLP0468 Métodos Quantitativos de Pesquisa na Ciência Política IV, de introdução à regressão, bem como o curso de pós-graduação, Métodos II.

Agradeço aos alunos do curso pelos feedbacks (futuros e presentes) sobre esse material, bem como ao monitor do curso, Davi Veronese.

Futuramente, pretendo transformar as notas de aulas em um livro, que poderá ser utilizado pela comunidade brasileira de ciências sociais interessada em aprender mais sobre métodos quantitativos, em particular regressão com R.

A motivação para disponibilizar as notas de aula em formato de livro é a quase inexistência de um material bom de econometria básica, em português, voltado para a área de ciências sociais, em particular a ciência política. Existem bons manuais em inglês para ciência política e bons manuais em português para economia, mas não em portugês para ciência política.

Além disso, os livros existentes nem sempre fazem um bom trabalho de diferenciar regressão estatística e modelo estrutural (causal) de regressão. Uma abordagem moderna de inferência causal requer que essa distinção seja ensinada ao aluno e esse livro também pretende preencher essa lacuna.

Por fim, a utilização do R é uma forma de dar ênfase à parte prática. Embora a teoria seja importante e a boa compreensão dos fundamentos é o que permite o aprofundamento dos temas cobertos no livro, estatística é uma disciplina aplicada, cujo maior valor está na sua aplicação prática. Assim, boa parte do curso e do conteúdo do livro é dedicado a implementar a teoria no R, bem como na interpretação dos dados.

O livro começa com  capítulos iniciais de introdução/revisão do R e de estatística básica (incluindo probabilidade). Assim, pressupomos que um estudante que utilize esse curso tenha conhecimentos de estatística e probabilidade básica. Não é necessário conhecimento previo de R, nem de cálculo ou álgebra linerar.

O restante do livro está organizado da seguinte maneira. Após as revisões, o texto introduz o conceito de esperança condicional, para motivar a regressão como aproximação da esperança condicional. Apresentamos então alguns estimadores (plug-in estimators e MQO), para então discutir causalidade, a partir da abordagem de resultados potenciais. Mostramso então estimação por Máxima Verossimilhança e checagem do modelo. Seguinos a ordem do livro do Cosma Shalizi (The Truth About Linear Regression), de discutir checagem antes de inferência, pois esta depende dos presssupostos serem válidos. Passamos então à inferência, regressão múltipla e por fim uma rápida introdução à regressão logística.

As referências principais para o presente livro são o já referido livro do Shalizi, além do manual consagrado do Hansen, Econometrics. O capítulo de resultados potenciais e intepretação da regrexão como aproximação da CEF beberam extensamente do livro de Angrrst e Pschike, Mostly Harmless Econometris, e o capítulo sobre logística do Livro de Gelman, Hill e vehtari, Regression and other Stories. O leitor atento verá que várias derivações seguem fielmente o que se encontra nesse livros.

Por fim, destaco a discussão sobre análise de sensibilidade, ausente de todos os manuais de econometria que olhei. Ainda um tanto confusa, creio que é tópico fundamental e da fronteira das análises causais e que acho uma boa contribuição (quando revisar o texto) para quem se interesse por análise causal e não encontra tutoriais sobre o tema disponível, nem mesmo na internet.
