<!DOCTYPE html>
<html lang="pt" xml:lang="pt">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 5 O Modelo de Regressão | Introdução à Regresssão para Ciências Sociais</title>
  <meta name="description" content="Capítulo 5 O Modelo de Regressão | Introdução à Regresssão para Ciências Sociais" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 5 O Modelo de Regressão | Introdução à Regresssão para Ciências Sociais" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 5 O Modelo de Regressão | Introdução à Regresssão para Ciências Sociais" />
  
  
  

<meta name="author" content="Manoel Galdino" />


<meta name="date" content="2025-09-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introdução-à-simulação.html"/>
<link rel="next" href="cef-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introdução à Regressão</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="05-intro_reg.html"><a href="#pref%C3%A1cio"><i class="fa fa-check"></i><b>1</b> - Prefácio</a></li>
<li class="chapter" data-level="2" data-path="05-intro_reg.html"><a href="#revis%C3%A3o-de-r"><i class="fa fa-check"></i><b>2</b> - Revisão de R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="revisão-de-r.html"><a href="revisão-de-r.html"><i class="fa fa-check"></i><b>2.1</b> R e Rstudio</a></li>
<li class="chapter" data-level="2.2" data-path="revisão-de-r.html"><a href="revisão-de-r.html#r-como-calculadora"><i class="fa fa-check"></i><b>2.2</b> R como calculadora</a></li>
<li class="chapter" data-level="2.3" data-path="revisão-de-r.html"><a href="revisão-de-r.html#objetos-no-r"><i class="fa fa-check"></i><b>2.3</b> Objetos no R</a></li>
<li class="chapter" data-level="2.4" data-path="revisão-de-r.html"><a href="revisão-de-r.html#tipos-de-objetos"><i class="fa fa-check"></i><b>2.4</b> Tipos de objetos</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="revisão-de-r.html"><a href="revisão-de-r.html#numeric"><i class="fa fa-check"></i><b>2.4.1</b> Numeric</a></li>
<li class="chapter" data-level="2.4.2" data-path="revisão-de-r.html"><a href="revisão-de-r.html#character"><i class="fa fa-check"></i><b>2.4.2</b> character</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="revisão-de-r.html"><a href="revisão-de-r.html#armazenando-dados"><i class="fa fa-check"></i><b>2.5</b> Armazenando dados</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="revisão-de-r.html"><a href="revisão-de-r.html#vetor"><i class="fa fa-check"></i><b>2.5.1</b> Vetor</a></li>
<li class="chapter" data-level="2.5.2" data-path="revisão-de-r.html"><a href="revisão-de-r.html#matriz"><i class="fa fa-check"></i><b>2.5.2</b> Matriz</a></li>
<li class="chapter" data-level="2.5.3" data-path="revisão-de-r.html"><a href="revisão-de-r.html#data-frame"><i class="fa fa-check"></i><b>2.5.3</b> Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="revisão-de-r.html"><a href="revisão-de-r.html#bibliotecaspacotes"><i class="fa fa-check"></i><b>2.6</b> Bibliotecas/pacotes</a></li>
<li class="chapter" data-level="2.7" data-path="revisão-de-r.html"><a href="revisão-de-r.html#importando-dados"><i class="fa fa-check"></i><b>2.7</b> importando dados</a></li>
<li class="chapter" data-level="2.8" data-path="revisão-de-r.html"><a href="revisão-de-r.html#data-wrangling"><i class="fa fa-check"></i><b>2.8</b> Data wrangling</a></li>
<li class="chapter" data-level="2.9" data-path="05-intro_reg.html"><a href="#visualiza%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>2.9</b> Visualização</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="05-intro_reg.html"><a href="#revis%C3%A3o-de-estat%C3%ADstica-e-probabilidade"><i class="fa fa-check"></i><b>3</b> - Revisão de estatística e probabilidade</a>
<ul>
<li class="chapter" data-level="3.1" data-path="05-intro_reg.html"><a href="#vari%C3%A1vel-aleat%C3%B3ria"><i class="fa fa-check"></i><b>3.1</b> Variável Aleatória</a></li>
<li class="chapter" data-level="3.2" data-path="05-intro_reg.html"><a href="#esperan%C3%A7a-matem%C3%A1tica"><i class="fa fa-check"></i><b>3.2</b> Esperança matemática</a></li>
<li class="chapter" data-level="3.3" data-path="05-intro_reg.html"><a href="#vari%C3%A2ncia"><i class="fa fa-check"></i><b>3.3</b> Variância</a></li>
<li class="chapter" data-level="3.4" data-path="05-intro_reg.html"><a href="#%C3%A1lgebra-com-esperan%C3%A7a-vari%C3%A2ncia-e-covari%C3%A2ncia"><i class="fa fa-check"></i><b>3.4</b> Álgebra com Esperança, Variância e Covariância</a></li>
<li class="chapter" data-level="3.5" data-path="05-intro_reg.html"><a href="#prova-da-identidade-da-vari%C3%A2ncia"><i class="fa fa-check"></i><b>3.5</b> Prova da identidade da variância</a></li>
<li class="chapter" data-level="3.6" data-path="05-intro_reg.html"><a href="#distribui%C3%A7%C3%A3o-de-probabilidade-conjunta"><i class="fa fa-check"></i><b>3.6</b> Distribuição de Probabilidade Conjunta</a></li>
<li class="chapter" data-level="3.7" data-path="revisão-de-estatística-e-probabilidade.html"><a href="revisão-de-estatística-e-probabilidade.html"><i class="fa fa-check"></i><b>3.7</b> Probabilidade Condicional</a></li>
<li class="chapter" data-level="3.8" data-path="05-intro_reg.html"><a href="#esperan%C3%A7a-condicional"><i class="fa fa-check"></i><b>3.8</b> Esperança Condicional</a></li>
<li class="chapter" data-level="3.9" data-path="05-intro_reg.html"><a href="#proje%C3%A7%C3%A3o-linear"><i class="fa fa-check"></i><b>3.9</b> Projeção Linear</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="05-intro_reg.html"><a href="#adi%C3%A7%C3%A3o-de-vetores"><i class="fa fa-check"></i><b>3.9.1</b> Adição de vetores</a></li>
<li class="chapter" data-level="3.9.2" data-path="05-intro_reg.html"><a href="#proje%C3%A7%C3%A3o-linear-1"><i class="fa fa-check"></i><b>3.9.2</b> Projeção linear</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="05-intro_reg.html"><a href="#introdu%C3%A7%C3%A3o-%C3%A0-simula%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>4</b> Introdução à Simulação</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introdução-à-simulação.html"><a href="introdução-à-simulação.html"><i class="fa fa-check"></i><b>4.1</b> Objetivos</a></li>
<li class="chapter" data-level="4.2" data-path="05-intro_reg.html"><a href="#introdu%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>4.2</b> Introdução</a></li>
<li class="chapter" data-level="4.3" data-path="introdução-à-simulação.html"><a href="introdução-à-simulação.html#dgp-processo-gerador-de-dados"><i class="fa fa-check"></i><b>4.3</b> DGP — Processo Gerador de Dados</a></li>
<li class="chapter" data-level="4.4" data-path="05-intro_reg.html"><a href="#simula%C3%A7%C3%A3o-de-monte-carlo"><i class="fa fa-check"></i><b>4.4</b> Simulação de Monte Carlo</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="introdução-à-simulação.html"><a href="introdução-à-simulação.html#simulando-um-dado"><i class="fa fa-check"></i><b>4.4.1</b> Simulando um dado</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="05-intro_reg.html"><a href="#configura%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>4.5</b> Configuração</a></li>
<li class="chapter" data-level="4.6" data-path="introdução-à-simulação.html"><a href="introdução-à-simulação.html#simular"><i class="fa fa-check"></i><b>4.6</b> Simular</a></li>
<li class="chapter" data-level="4.7" data-path="introdução-à-simulação.html"><a href="introdução-à-simulação.html#resumir"><i class="fa fa-check"></i><b>4.7</b> Resumir</a></li>
<li class="chapter" data-level="4.8" data-path="introdução-à-simulação.html"><a href="introdução-à-simulação.html#lgn-e-tcl"><i class="fa fa-check"></i><b>4.8</b> LGN e TCL</a></li>
<li class="chapter" data-level="4.9" data-path="introdução-à-simulação.html"><a href="introdução-à-simulação.html#cobertura-de-um-ic"><i class="fa fa-check"></i><b>4.9</b> Cobertura de um IC</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="05-intro_reg.html"><a href="#o-modelo-de-regress%C3%A3o"><i class="fa fa-check"></i><b>5</b> O Modelo de Regressão</a>
<ul>
<li class="chapter" data-level="5.1" data-path="05-intro_reg.html"><a href="#modelo-de-regress%C3%A3o---teoria"><i class="fa fa-check"></i><b>5.1</b> Modelo de Regressão - Teoria</a></li>
<li class="chapter" data-level="5.2" data-path="o-modelo-de-regressão.html"><a href="o-modelo-de-regressão.html"><i class="fa fa-check"></i><b>5.2</b> CEF</a></li>
<li class="chapter" data-level="5.3" data-path="o-modelo-de-regressão.html"><a href="o-modelo-de-regressão.html#cef-e-voto"><i class="fa fa-check"></i><b>5.3</b> CEF e voto</a></li>
<li class="chapter" data-level="5.4" data-path="o-modelo-de-regressão.html"><a href="o-modelo-de-regressão.html#algumas-propriedades-da-cef"><i class="fa fa-check"></i><b>5.4</b> Algumas Propriedades da CEF</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="05-intro_reg.html"><a href="#cef-%C3%A9-a-melhor-aproxima%C3%A7%C3%A3o-aos-dados"><i class="fa fa-check"></i><b>5.4.1</b> CEF é a melhor aproximação aos dados</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="05-intro_reg.html"><a href="#regress%C3%A3o-linear"><i class="fa fa-check"></i><b>5.5</b> Regressão Linear</a></li>
<li class="chapter" data-level="5.6" data-path="o-modelo-de-regressão.html"><a href="o-modelo-de-regressão.html#logaritmos"><i class="fa fa-check"></i><b>5.6</b> Logaritmos</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="05-intro_reg.html"><a href="#logartimos-como-diferen%C3%A7a-de-porcentagens"><i class="fa fa-check"></i><b>5.6.1</b> Logartimos como diferença de porcentagens</a></li>
<li class="chapter" data-level="5.6.2" data-path="05-intro_reg.html"><a href="#logaritmos-e-m%C3%A9dia-geom%C3%A9trica"><i class="fa fa-check"></i><b>5.6.2</b> Logaritmos e média geométrica</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="05-intro_reg.html"><a href="#prevendo-a-partir-da-esperan%C3%A7a-condicional"><i class="fa fa-check"></i><b>5.7</b> Prevendo a partir da esperança condicional</a></li>
<li class="chapter" data-level="5.8" data-path="o-modelo-de-regressão.html"><a href="o-modelo-de-regressão.html#preditores-lineares"><i class="fa fa-check"></i><b>5.8</b> Preditores lineares</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="cef-1.html"><a href="cef-1.html"><i class="fa fa-check"></i><b>6</b> - CEF</a>
<ul>
<li class="chapter" data-level="6.1" data-path="cef-1.html"><a href="cef-1.html#erro-da-cef"><i class="fa fa-check"></i><b>6.1</b> Erro da CEF</a></li>
<li class="chapter" data-level="6.2" data-path="cef-1.html"><a href="cef-1.html#simulando-para-entender-a-cef"><i class="fa fa-check"></i><b>6.2</b> Simulando para entender a CEF</a></li>
<li class="chapter" data-level="6.3" data-path="cef-1.html"><a href="cef-1.html#propriedades-da-cef"><i class="fa fa-check"></i><b>6.3</b> Propriedades da CEF</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="05-intro_reg.html"><a href="#a-esperan%C3%A7a-do-erro-condicional-a-x-%C3%A9-zero"><i class="fa fa-check"></i><b>6.3.1</b> A Esperança do Erro Condicional a X é zero</a></li>
<li class="chapter" data-level="6.3.2" data-path="05-intro_reg.html"><a href="#a-esperan%C3%A7a-n%C3%A3o-condicional-do-erro-%C3%A9-zero."><i class="fa fa-check"></i><b>6.3.2</b> A esperança (não-condicional) do erro é zero.</a></li>
<li class="chapter" data-level="6.3.3" data-path="05-intro_reg.html"><a href="#o-erro-da-cef-%C3%A9-n%C3%A3o-correlacionado-com-x"><i class="fa fa-check"></i><b>6.3.3</b> O erro da CEF é não-correlacionado com X</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="05-intro_reg.html"><a href="#regress%C3%A3o-linear-e-a-cef"><i class="fa fa-check"></i><b>6.4</b> Regressão Linear e a CEF</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="05-intro_reg.html"><a href="#m%C3%ADnimos-quadrados-ordin%C3%A1rios"><i class="fa fa-check"></i><b>6.4.1</b> Mínimos Quadrados Ordinários</a></li>
<li class="chapter" data-level="6.4.2" data-path="05-intro_reg.html"><a href="#suponha-que-a-cef-%C3%A9-linear-justificativa-i"><i class="fa fa-check"></i><b>6.4.2</b> Suponha que a CEF é Linear (Justificativa I)</a></li>
<li class="chapter" data-level="6.4.3" data-path="05-intro_reg.html"><a href="#%C3%A9-o-melhor-preditor-linear-do-y-justificativa-ii"><i class="fa fa-check"></i><b>6.4.3</b> É o melhor preditor linear do <span class="math inline">\(Y\)</span> (justificativa II)</a></li>
<li class="chapter" data-level="6.4.4" data-path="05-intro_reg.html"><a href="#a-reta-de-regress%C3%A3o-%C3%A9-a-aproxima%C3%A7%C3%A3o-com-o-menor-erro-quadr%C3%A1tico-m%C3%A9dio-justificativa-iii"><i class="fa fa-check"></i><b>6.4.4</b> A reta de regressão é a aproximação com o menor erro quadrático médio (justificativa III)</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="cef-1.html"><a href="cef-1.html#linearidade-e-causalidade"><i class="fa fa-check"></i><b>6.5</b> Linearidade e Causalidade</a></li>
<li class="chapter" data-level="6.6" data-path="05-intro_reg.html"><a href="#modelo-s%C3%B3-com-intercepto"><i class="fa fa-check"></i><b>6.6</b> Modelo só com intercepto</a></li>
<li class="chapter" data-level="6.7" data-path="05-intro_reg.html"><a href="#vari%C3%A2ncia-da-regress%C3%A3o"><i class="fa fa-check"></i><b>6.7</b> Variância da Regressão</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="cef-1.html"><a href="cef-1.html#chuva-na-jamaica"><i class="fa fa-check"></i><b>6.7.1</b> Chuva na Jamaica</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="05-intro_reg.html"><a href="#vari%C3%A2ncia-condicional"><i class="fa fa-check"></i><b>6.8</b> Variância condicional</a></li>
<li class="chapter" data-level="6.9" data-path="cef-1.html"><a href="cef-1.html#efeito-marginal"><i class="fa fa-check"></i><b>6.9</b> Efeito Marginal</a></li>
<li class="chapter" data-level="6.10" data-path="05-intro_reg.html"><a href="#cef-linear-com-preditores-n%C3%A3o-lineares"><i class="fa fa-check"></i><b>6.10</b> CEF linear com preditores não-lineares</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="05-intro_reg.html"><a href="#estima%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>7</b> - Estimação</a>
<ul>
<li class="chapter" data-level="7.1" data-path="estimação.html"><a href="estimação.html"><i class="fa fa-check"></i><b>7.1</b> Plug-in estimators</a></li>
<li class="chapter" data-level="7.2" data-path="estimação.html"><a href="estimação.html#simulando-de-uma-normal-bivariada"><i class="fa fa-check"></i><b>7.2</b> Simulando de uma Normal Bivariada</a></li>
<li class="chapter" data-level="7.3" data-path="05-intro_reg.html"><a href="#suposi%C3%A7%C3%B5es-amostrais-de-mqo"><i class="fa fa-check"></i><b>7.3</b> Suposições amostrais de MQO</a></li>
<li class="chapter" data-level="7.4" data-path="05-intro_reg.html"><a href="#modelo-de-m%C3%A9dia-amostral"><i class="fa fa-check"></i><b>7.4</b> Modelo de Média amostral</a></li>
<li class="chapter" data-level="7.5" data-path="05-intro_reg.html"><a href="#modelo-de-regress%C3%A3o-linear-com-preditores"><i class="fa fa-check"></i><b>7.5</b> Modelo de Regressão Linear com preditores</a></li>
<li class="chapter" data-level="7.6" data-path="05-intro_reg.html"><a href="#vari%C3%A2ncia-do-estimador"><i class="fa fa-check"></i><b>7.6</b> Variância do estimador</a></li>
<li class="chapter" data-level="7.7" data-path="05-intro_reg.html"><a href="#estimando-um-modelo-de-regress%C3%A3o-real"><i class="fa fa-check"></i><b>7.7</b> Estimando um modelo de regressão real</a></li>
<li class="chapter" data-level="7.8" data-path="05-intro_reg.html"><a href="#limita%C3%A7%C3%B5es-de-mqo"><i class="fa fa-check"></i><b>7.8</b> Limitações de MQO</a></li>
<li class="chapter" data-level="7.9" data-path="05-intro_reg.html"><a href="#distra%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>7.9</b> Distrações</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="estimação.html"><a href="estimação.html#r-quadrado"><i class="fa fa-check"></i><b>7.9.1</b> R-quadrado</a></li>
<li class="chapter" data-level="7.9.2" data-path="estimação.html"><a href="estimação.html#r-quadrado-ajustado"><i class="fa fa-check"></i><b>7.9.2</b> R-quadrado ajustado</a></li>
<li class="chapter" data-level="7.9.3" data-path="estimação.html"><a href="estimação.html#limites-do-r-quadrado"><i class="fa fa-check"></i><b>7.9.3</b> Limites do R-quadrado</a></li>
<li class="chapter" data-level="7.9.4" data-path="estimação.html"><a href="estimação.html#para-que-serve"><i class="fa fa-check"></i><b>7.9.4</b> Para que serve?</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="05-intro_reg.html"><a href="#demonstra%C3%A7%C3%A3o-alternativa-que-estimador-%C3%A9-n%C3%A3o-viesado."><i class="fa fa-check"></i><b>7.10</b> Demonstração Alternativa que estimador é não-viesado.</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="causalidade.html"><a href="causalidade.html"><i class="fa fa-check"></i><b>8</b> - Causalidade</a>
<ul>
<li class="chapter" data-level="8.1" data-path="causalidade.html"><a href="causalidade.html#resultados-potenciais"><i class="fa fa-check"></i><b>8.1</b> Resultados Potenciais</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="05-intro_reg.html"><a href="#decomposi%C3%A7%C3%A3o-do-efeito-causal"><i class="fa fa-check"></i><b>8.1.1</b> Decomposição do Efeito Causal</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="05-intro_reg.html"><a href="#modelo-estrutural-e-modelo-de-regress%C3%A3o"><i class="fa fa-check"></i><b>8.2</b> Modelo estrutural e modelo de regressão</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="causalidade.html"><a href="causalidade.html#exemplo-de-cef-e-cef-estrutural"><i class="fa fa-check"></i><b>8.2.1</b> Exemplo de CEF e CEF estrutural</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="05-intro_reg.html"><a href="#simula%C3%A7%C3%A3o-de-resultados-potenciais-e-causalidade"><i class="fa fa-check"></i><b>8.3</b> Simulação de Resultados Potenciais e Causalidade</a></li>
<li class="chapter" data-level="8.4" data-path="05-intro_reg.html"><a href="#refer%C3%AAncias"><i class="fa fa-check"></i><b>8.4</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="mle.html"><a href="mle.html"><i class="fa fa-check"></i><b>9</b> - MLE</a>
<ul>
<li class="chapter" data-level="9.1" data-path="05-intro_reg.html"><a href="#estima%C3%A7%C3%A3o-por-m%C3%A1xima-verossimilhan%C3%A7a"><i class="fa fa-check"></i><b>9.1</b> Estimação por Máxima Verossimilhança</a></li>
<li class="chapter" data-level="9.2" data-path="05-intro_reg.html"><a href="#teste-de-hip%C3%B3tese"><i class="fa fa-check"></i><b>9.2</b> Teste de hipótese</a></li>
<li class="chapter" data-level="9.3" data-path="05-intro_reg.html"><a href="#regress%C3%A3o"><i class="fa fa-check"></i><b>9.3</b> regressão</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="checagem.html"><a href="checagem.html"><i class="fa fa-check"></i><b>10</b> - Checagem</a>
<ul>
<li class="chapter" data-level="10.1" data-path="05-intro_reg.html"><a href="#res%C3%ADduos"><i class="fa fa-check"></i><b>10.1</b> Resíduos</a></li>
<li class="chapter" data-level="10.2" data-path="checagem.html"><a href="checagem.html#modelo-no-r"><i class="fa fa-check"></i><b>10.2</b> Modelo no R</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="05-intro_reg.html"><a href="#res%C3%ADduos-contra-o-preditor"><i class="fa fa-check"></i><b>10.2.1</b> Resíduos contra o preditor</a></li>
<li class="chapter" data-level="10.2.2" data-path="05-intro_reg.html"><a href="#magnitude-dos-res%C3%ADduos-contra-o-preditor"><i class="fa fa-check"></i><b>10.2.2</b> Magnitude dos Resíduos Contra o Preditor</a></li>
<li class="chapter" data-level="10.2.3" data-path="05-intro_reg.html"><a href="#res%C3%ADduos-com-dados-temporais-eou-espaciais"><i class="fa fa-check"></i><b>10.2.3</b> Resíduos com dados Temporais e/ou Espaciais</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="05-intro_reg.html"><a href="#normalidade-dos-res%C3%ADduos"><i class="fa fa-check"></i><b>10.3</b> Normalidade dos resíduos</a></li>
<li class="chapter" data-level="10.4" data-path="05-intro_reg.html"><a href="#generaliza%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>10.4</b> Generalização</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="inferencia.html"><a href="inferencia.html"><i class="fa fa-check"></i><b>11</b> - Inferencia</a>
<ul>
<li class="chapter" data-level="11.1" data-path="inferencia.html"><a href="inferencia.html#normal"><i class="fa fa-check"></i><b>11.1</b> Normal</a></li>
<li class="chapter" data-level="11.2" data-path="inferencia.html"><a href="inferencia.html#t-student"><i class="fa fa-check"></i><b>11.2</b> T-student</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="05-intro_reg.html"><a href="#avan%C3%A7ado---deriva%C3%A7%C3%A3o-da-t--de-student"><i class="fa fa-check"></i><b>11.2.1</b> Avançado - Derivação da t- de student</a></li>
<li class="chapter" data-level="11.2.2" data-path="inferencia.html"><a href="inferencia.html#teste-t"><i class="fa fa-check"></i><b>11.2.2</b> Teste t</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="05-intro_reg.html"><a href="#teste-de-hip%C3%B3tese-e-ic"><i class="fa fa-check"></i><b>11.3</b> Teste de Hipótese e IC</a></li>
<li class="chapter" data-level="11.4" data-path="05-intro_reg.html"><a href="#propriedades-assint%C3%B3ticas"><i class="fa fa-check"></i><b>11.4</b> Propriedades Assintóticas</a></li>
<li class="chapter" data-level="11.5" data-path="05-intro_reg.html"><a href="#infer%C3%AAncia-preditiva"><i class="fa fa-check"></i><b>11.5</b> Inferência Preditiva</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="regressao-multipla.html"><a href="regressao-multipla.html"><i class="fa fa-check"></i><b>12</b> - Regressao Multipla</a>
<ul>
<li class="chapter" data-level="12.1" data-path="05-intro_reg.html"><a href="#revis%C3%A3o-de-matriz-e-vetores"><i class="fa fa-check"></i><b>12.1</b> Revisão de Matriz e Vetores</a></li>
<li class="chapter" data-level="12.2" data-path="05-intro_reg.html"><a href="#modelo-b%C3%A1sico"><i class="fa fa-check"></i><b>12.2</b> Modelo básico</a></li>
<li class="chapter" data-level="12.3" data-path="regressao-multipla.html"><a href="regressao-multipla.html#modelo-com-matrizes"><i class="fa fa-check"></i><b>12.3</b> Modelo com matrizes</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="regressao-multipla.html"><a href="regressao-multipla.html#estimador-de-mqo"><i class="fa fa-check"></i><b>12.3.1</b> Estimador de MQO</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="05-intro_reg.html"><a href="#interpreta%C3%A7%C3%A3o-dos-coeficientes"><i class="fa fa-check"></i><b>12.4</b> Interpretação dos coeficientes</a></li>
<li class="chapter" data-level="12.5" data-path="05-intro_reg.html"><a href="#regress%C3%A3o-m%C3%BAltipla-versus-m%C3%BAltiplas-regress%C3%B5es-separadas-ou-vi%C3%A9s-de-vari%C3%A1vel-omitida"><i class="fa fa-check"></i><b>12.5</b> Regressão múltipla versus Múltiplas Regressões Separadas ou Viés de variável omitida</a></li>
<li class="chapter" data-level="12.6" data-path="05-intro_reg.html"><a href="#matriz-chap%C3%A9u"><i class="fa fa-check"></i><b>12.6</b> Matriz chapéu</a></li>
<li class="chapter" data-level="12.7" data-path="regressao-multipla.html"><a href="regressao-multipla.html#multicolinearidade"><i class="fa fa-check"></i><b>12.7</b> Multicolinearidade</a></li>
<li class="chapter" data-level="12.8" data-path="05-intro_reg.html"><a href="#erro-padr%C3%A3o-robusto"><i class="fa fa-check"></i><b>12.8</b> Erro padrão Robusto</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="05-intro_reg.html"><a href="#entendendo-o-erro-padr%C3%A3o-robusto"><i class="fa fa-check"></i><b>12.8.1</b> Entendendo o erro padrão robusto</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="05-intro_reg.html"><a href="#termo-de-intera%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>12.9</b> Termo de interação</a>
<ul>
<li class="chapter" data-level="12.9.1" data-path="05-intro_reg.html"><a href="#vari%C3%A2ncia-do-termo-de-intera%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>12.9.1</b> Variância do termo de interação</a></li>
<li class="chapter" data-level="12.9.2" data-path="05-intro_reg.html"><a href="#calculando-o-erro-padr%C3%A3o-do-termo-de-intera%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>12.9.2</b> Calculando o erro padrão do termo de interação</a></li>
</ul></li>
<li class="chapter" data-level="12.10" data-path="05-intro_reg.html"><a href="#an%C3%A1lise-de-sensibilidade-causal"><i class="fa fa-check"></i><b>12.10</b> Análise de sensibilidade causal</a>
<ul>
<li class="chapter" data-level="12.10.1" data-path="05-intro_reg.html"><a href="#deriva%C3%A7%C3%A3o-do-r-quadrado"><i class="fa fa-check"></i><b>12.10.1</b> Derivação do R-quadrado</a></li>
<li class="chapter" data-level="12.10.2" data-path="05-intro_reg.html"><a href="#vi%C3%A9s-de-vari%C3%A1vel-omitida"><i class="fa fa-check"></i><b>12.10.2</b> Viés de variável omitida</a></li>
<li class="chapter" data-level="12.10.3" data-path="05-intro_reg.html"><a href="#vi%C3%A9s-de-vari%C3%A1vel-omitida-em-fun%C3%A7%C3%A3o-do-r-quadrado"><i class="fa fa-check"></i><b>12.10.3</b> Viés de variável omitida em função do R-quadrado</a></li>
</ul></li>
<li class="chapter" data-level="12.11" data-path="05-intro_reg.html"><a href="#refer%C3%AAncias-1"><i class="fa fa-check"></i><b>12.11</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>13</b> - GLM</a>
<ul>
<li class="chapter" data-level="13.1" data-path="glm.html"><a href="glm.html#plm"><i class="fa fa-check"></i><b>13.1</b> PLM</a></li>
<li class="chapter" data-level="13.2" data-path="05-intro_reg.html"><a href="#log%C3%ADstica"><i class="fa fa-check"></i><b>13.2</b> Logística</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="05-intro_reg.html"><a href="#log%C3%ADstica-como-melhoria-em-rela%C3%A7%C3%A3o-ao-mpl"><i class="fa fa-check"></i><b>13.2.1</b> Logística como melhoria em relação ao MPL</a></li>
<li class="chapter" data-level="13.2.2" data-path="glm.html"><a href="glm.html#logito"><i class="fa fa-check"></i><b>13.2.2</b> Logito</a></li>
<li class="chapter" data-level="13.2.3" data-path="05-intro_reg.html"><a href="#odds-ratio---raz%C3%A3o-de-chances"><i class="fa fa-check"></i><b>13.2.3</b> Odds Ratio - Razão de chances</a></li>
<li class="chapter" data-level="13.2.4" data-path="05-intro_reg.html"><a href="#coeficientes-e-erros-padr%C3%B5es"><i class="fa fa-check"></i><b>13.2.4</b> Coeficientes e erros padrões</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="05-intro_reg.html"><a href="#log%C3%ADstica-como-vari%C3%A1vel-latente"><i class="fa fa-check"></i><b>13.3</b> Logística como variável latente</a></li>
<li class="chapter" data-level="13.4" data-path="glm.html"><a href="glm.html#probit"><i class="fa fa-check"></i><b>13.4</b> Probit</a></li>
<li class="chapter" data-level="13.5" data-path="05-intro_reg.html"><a href="#log%C3%ADstica-como-glm"><i class="fa fa-check"></i><b>13.5</b> Logística como GLM</a></li>
<li class="chapter" data-level="13.6" data-path="05-intro_reg.html"><a href="#log%C3%ADstica-com-m%C3%BAltiplos-preditores"><i class="fa fa-check"></i><b>13.6</b> Logística com múltiplos preditores</a></li>
<li class="chapter" data-level="13.7" data-path="glm.html"><a href="glm.html#ajuste-do-modelo"><i class="fa fa-check"></i><b>13.7</b> Ajuste do modelo</a></li>
<li class="chapter" data-level="13.8" data-path="05-intro_reg.html"><a href="#regress%C3%A3o-com-dados-ordenados"><i class="fa fa-check"></i><b>13.8</b> Regressão com dados Ordenados</a></li>
<li class="chapter" data-level="13.9" data-path="05-intro_reg.html"><a href="#refer%C3%AAncias-2"><i class="fa fa-check"></i><b>13.9</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="05-intro_reg.html"><a href="#ap%C3%AAndice"><i class="fa fa-check"></i><b>14</b> - Apêndice</a>
<ul>
<li class="chapter" data-level="14.1" data-path="05-intro_reg.html"><a href="#importa%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>14.1</b> Importação</a></li>
<li class="chapter" data-level="14.2" data-path="05-intro_reg.html"><a href="#gr%C3%A1ficos-e-tabelas"><i class="fa fa-check"></i><b>14.2</b> Gráficos e Tabelas</a></li>
<li class="chapter" data-level="14.3" data-path="apêndice.html"><a href="apêndice.html"><i class="fa fa-check"></i><b>14.3</b> Limpeza de dados</a></li>
<li class="chapter" data-level="14.4" data-path="apêndice.html"><a href="apêndice.html#modelagem-de-dados"><i class="fa fa-check"></i><b>14.4</b> Modelagem de dados</a></li>
<li class="chapter" data-level="14.5" data-path="apêndice.html"><a href="apêndice.html#outros"><i class="fa fa-check"></i><b>14.5</b> Outros</a></li>
<li class="chapter" data-level="14.6" data-path="05-intro_reg.html"><a href="#%C3%A1lgebra-linear"><i class="fa fa-check"></i><b>14.6</b> Álgebra Linear</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="05-intro_reg.html"><a href="#espa%C3%A7o-de-vetores-e-subspa%C3%A7o"><i class="fa fa-check"></i><b>14.6.1</b> Espaço de vetores e subspaço</a></li>
<li class="chapter" data-level="14.6.2" data-path="05-intro_reg.html"><a href="#proje%C3%A7%C3%A3o-linear-2"><i class="fa fa-check"></i><b>14.6.2</b> Projeção linear</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="apêndice.html"><a href="apêndice.html#dados-espaciais"><i class="fa fa-check"></i><b>14.7</b> Dados Espaciais</a>
<ul>
<li class="chapter" data-level="14.7.1" data-path="05-intro_reg.html"><a href="#pol%C3%ADgonos"><i class="fa fa-check"></i><b>14.7.1</b> Polígonos</a></li>
<li class="chapter" data-level="14.7.2" data-path="apêndice.html"><a href="apêndice.html#econometria-espacial"><i class="fa fa-check"></i><b>14.7.2</b> Econometria espacial</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="teoremas.html"><a href="teoremas.html"><i class="fa fa-check"></i><b>15</b> - Teoremas</a>
<ul>
<li class="chapter" data-level="15.1" data-path="05-intro_reg.html"><a href="#independ%C3%AAncia-e-correla%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>15.1</b> Independência e Correlação</a></li>
<li class="chapter" data-level="15.2" data-path="teoremas.html"><a href="teoremas.html#propriedade-de-estimadores"><i class="fa fa-check"></i><b>15.2</b> Propriedade de estimadores</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="05-intro_reg.html"><a href="#vi%C3%A9s"><i class="fa fa-check"></i><b>15.2.1</b> Viés</a></li>
<li class="chapter" data-level="15.2.2" data-path="05-intro_reg.html"><a href="#vari%C3%A2ncia-1"><i class="fa fa-check"></i><b>15.2.2</b> Variância</a></li>
<li class="chapter" data-level="15.2.3" data-path="05-intro_reg.html"><a href="#efici%C3%AAncia"><i class="fa fa-check"></i><b>15.2.3</b> Eficiência</a></li>
<li class="chapter" data-level="15.2.4" data-path="05-intro_reg.html"><a href="#consist%C3%AAncia"><i class="fa fa-check"></i><b>15.2.4</b> Consistência</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="05-intro_reg.html"><a href="#exerc%C3%ADcios-para-o-leitor"><i class="fa fa-check"></i><b>15.3</b> Exercícios para o leitor</a></li>
<li class="chapter" data-level="15.4" data-path="05-intro_reg.html"><a href="#lei-das-esperan%C3%A7as-iteradas"><i class="fa fa-check"></i><b>15.4</b> Lei das Esperanças Iteradas</a></li>
<li class="chapter" data-level="15.5" data-path="teoremas.html"><a href="teoremas.html#teorema-do-condicionamento"><i class="fa fa-check"></i><b>15.5</b> Teorema do Condicionamento</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introdução à Regresssão para Ciências Sociais</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="o-modelo-de-regressão" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Capítulo 5</span> O Modelo de Regressão<a href="#o-modelo-de-regress%C3%A3o" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>“Prediction is hard. Specially about the future”. Fonte desconhecida.</p>
<div id="modelo-de-regressão---teoria" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Modelo de Regressão - Teoria<a href="#modelo-de-regress%C3%A3o---teoria" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O modelo de regressão (não confundir com regressão linear) é uma forma bem ampla de modelar os dados para prever uma variável de interesse, usualmente designada pela letra <span class="math inline">\(Y\)</span>. Se eu quero prever os votos de candidatas em uma eleição, a votação de cada candidata é minha variável de interesse, <span class="math inline">\(Y\)</span>. Digamos que eu tenho uma amostra da intenção de votos das candidatas, obtidas por meio de uma pesquisa eleitoral. Então, a regressão é uma forma de modelar os dados para prever justamente essa variável <span class="math inline">\(Y\)</span>.</p>
<p>Antes de entrarmos em Regressão, vale a pena repassar a nomenclatura básica sobre <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span>.</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabela-variaveis">Table 5.1: </span><span id="tab:tabela-variaveis">Table 5.2: </span>Nomenclaturas para Variáveis em Regressão Linear
</caption>
<thead>
<tr>
<th style="text-align:left;font-weight: bold;color: white !important;background-color: rgba(78, 93, 108, 255) !important;">
VD
</th>
<th style="text-align:left;font-weight: bold;color: white !important;background-color: rgba(78, 93, 108, 255) !important;">
VI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;color: blue !important;">
Variável Resposta
</td>
<td style="text-align:left;font-weight: bold;color: green !important;">
Variável Preditora
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: blue !important;">
Variável Explicada
</td>
<td style="text-align:left;font-weight: bold;color: green !important;">
Variável Explicativa
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: blue !important;">
Variável Predita
</td>
<td style="text-align:left;font-weight: bold;color: green !important;">
Variável de Entrada
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: blue !important;">
Variável de Saída
</td>
<td style="text-align:left;font-weight: bold;color: green !important;">
Variável Exógena
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: blue !important;">
Variável Regredida
</td>
<td style="text-align:left;font-weight: bold;color: green !important;">
Regressor
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: blue !important;">
Regressando
</td>
<td style="text-align:left;font-weight: bold;color: green !important;">
Covariável
</td>
</tr>
</tbody>
</table>
<p>Uma das primeiras distinções que temos de fazer é sobre previsão e explicação (causal). Quando queremos prever, estamos interessados em saber quais os provaveis valores de variáveis no futuro, a parte de informações sobre a própria variável e outras no passado. Nesse sentido, é preciso algum tipo de suposição de que o futuro se assemelha ao passado de algum modo. Esse tipo de suposição usualmente toma a forma de um modelo probabilísitco, mas não apenas.</p>
<p>Quando estamos interessados em explicações causais, temos dois tipos de perguntas de pesquisa possíveis. Uma sobre a chamada causa dos efeitos e outra sobre o efeito das causas (Gelman &amp; Imbens, 2013). A causa dos efeitos são perguntas do tipo: o que causal a II Grande Guerra? Ou qual a causa da eleição de Trump ou Bolsonaro? O que explica a desigualdade de renda no Brasil? São todas perguntas em que queremos explicar um efeito, isto é, identificar as causas de um fenômeno (efeito). Já o efeito das causas ão perguntas do tipo: qual o efeito da vacina de covid-19 sobre a mortalidade por Covid-19? Qual o efeito de checagem de notícias sobre a crença de pessoas em desinformação? Qual o efeito da magnitude eleitoral sobre fragmentação partidária? E assim por diante. Aqui, estamos interessados em entender o efeito causal de uma variável sobre outra, sem pretender esgotar todas as explicações de causa possíveis.</p>
<p>A maior parte dos métodos quantitativos existentes são bons para responder perguntas de previsão e de causa dos efeitos. Grosso modo, não há método quantitativo para estimação do efeito das causas, exceto realizar uma série de estudos independentes sobre várias causas dos efeitos, olhando uma causa distinta do mesmo efeito por vez e esperar que isso gere um conhecimento combinado sobre essas múltiplas causas. Mas não há, contudo, uma metodologia bem definida de como combinar esses estudos independentes em um único conhecimento do efeito conjunto das causas.</p>
<p>Assim, nosso curso será dedicado apenas a modelos de previsão e modelos de causa dos efeitos, que é o que temos de metodologias já desenvolvidas e consolidadas. Começamos por essa explicação porque uma perspectiva mais antiga, e ainda comum nas ciências sociais, é que modelos de regressão múltiplas permitem estimar o efeito de várias causas. Isso raramente é o caso e não adotaremos essa perspecitva aqui <a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>.</p>
<p>Há muitas formas de apresentar ou motivar regressão linear. O método mais tradicional é pensar que a regressão linear é uma reta que é ajustada aos pontos observados. Porém, não tomaremos esse caminho aqui.</p>
<p>Nós iremos considerar que a regressão linear é uma forma de aproximar a chamada “Conditional Regression Function” (CEF, na sigla em inglês). O objetivo é entender “as far as possible with the available data how the conditional distribution of some response <span class="math inline">\(y\)</span> varies across subpopulations determined by the possible values of the predictor or predictors” (Cook and Weisberg, apud Berk, p. 4).</p>
</div>
<div id="cef" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> CEF<a href="o-modelo-de-regressão.html#cef" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para introduzir a CEF, iremos trabalhar com um banco de dados de eleição. O código abaixo mostrar como importar e processar os dados.
O dado original foi retirado do portal de dados abertos do TSE, com os dados de votação nominal nas eleições de 2020 para o estado de São Paulo.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="o-modelo-de-regressão.html#cb71-1" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb71-2"><a href="o-modelo-de-regressão.html#cb71-2" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb71-3"><a href="o-modelo-de-regressão.html#cb71-3" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb71-4"><a href="o-modelo-de-regressão.html#cb71-4" tabindex="-1"></a><span class="co"># Importando os dados desejados</span></span>
<span id="cb71-5"><a href="o-modelo-de-regressão.html#cb71-5" tabindex="-1"></a></span>
<span id="cb71-6"><a href="o-modelo-de-regressão.html#cb71-6" tabindex="-1"></a><span class="co"># dados &lt;- fread(here(&quot;dados\\votacao_secao_2020_SP\\&quot;, &quot;votacao_secao_2020_SP.csv&quot;), encoding = &quot;Latin-1&quot;)</span></span></code></pre></div>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="o-modelo-de-regressão.html#cb72-1" tabindex="-1"></a><span class="co"># dados_finais &lt;- dados %&gt;%</span></span>
<span id="cb72-2"><a href="o-modelo-de-regressão.html#cb72-2" tabindex="-1"></a><span class="co">#   dplyr::filter(DS_CARGO == &quot;Prefeito&quot; &amp; ANO_ELEICAO == 2020 &amp; NM_TIPO_ELEICAO == &quot;Eleição Ordinária&quot;) %&gt;%</span></span>
<span id="cb72-3"><a href="o-modelo-de-regressão.html#cb72-3" tabindex="-1"></a><span class="co">#   group_by(DS_ELEICAO, NR_TURNO, NM_MUNICIPIO, </span></span>
<span id="cb72-4"><a href="o-modelo-de-regressão.html#cb72-4" tabindex="-1"></a><span class="co">#            NR_ZONA, NR_SECAO, NR_VOTAVEL) %&gt;%</span></span>
<span id="cb72-5"><a href="o-modelo-de-regressão.html#cb72-5" tabindex="-1"></a><span class="co">#   summarise(votos_nominais = sum(QT_VOTOS)) </span></span>
<span id="cb72-6"><a href="o-modelo-de-regressão.html#cb72-6" tabindex="-1"></a><span class="co"># saveRDS(dados_finais, file=here(&quot;dados\\&quot;, &quot;dados_finais.rds&quot;))</span></span>
<span id="cb72-7"><a href="o-modelo-de-regressão.html#cb72-7" tabindex="-1"></a></span>
<span id="cb72-8"><a href="o-modelo-de-regressão.html#cb72-8" tabindex="-1"></a><span class="co">#salvei os dados e posso importar o que fiz.</span></span>
<span id="cb72-9"><a href="o-modelo-de-regressão.html#cb72-9" tabindex="-1"></a><span class="co"># o arquivo dados_finais.rds está no respositório em:</span></span>
<span id="cb72-10"><a href="o-modelo-de-regressão.html#cb72-10" tabindex="-1"></a><span class="co"># https://github.com/mgaldino/book-regression/tree/main/dados</span></span>
<span id="cb72-11"><a href="o-modelo-de-regressão.html#cb72-11" tabindex="-1"></a>dados_finais <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">here</span>(<span class="st">&quot;dados&quot;</span>, <span class="st">&quot;dados_finais.rds&quot;</span>))</span>
<span id="cb72-12"><a href="o-modelo-de-regressão.html#cb72-12" tabindex="-1"></a></span>
<span id="cb72-13"><a href="o-modelo-de-regressão.html#cb72-13" tabindex="-1"></a><span class="co"># Identificar os municípios que possuem segundo turno</span></span>
<span id="cb72-14"><a href="o-modelo-de-regressão.html#cb72-14" tabindex="-1"></a>municipios_segundo_turno <span class="ot">&lt;-</span> dados_finais <span class="sc">%&gt;%</span></span>
<span id="cb72-15"><a href="o-modelo-de-regressão.html#cb72-15" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb72-16"><a href="o-modelo-de-regressão.html#cb72-16" tabindex="-1"></a>  <span class="fu">filter</span>(NR_TURNO <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb72-17"><a href="o-modelo-de-regressão.html#cb72-17" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(NM_MUNICIPIO) <span class="sc">%&gt;%</span></span>
<span id="cb72-18"><a href="o-modelo-de-regressão.html#cb72-18" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb72-19"><a href="o-modelo-de-regressão.html#cb72-19" tabindex="-1"></a></span>
<span id="cb72-20"><a href="o-modelo-de-regressão.html#cb72-20" tabindex="-1"></a><span class="co"># Filtrar os dados para incluir apenas os municípios que têm segundo turno</span></span>
<span id="cb72-21"><a href="o-modelo-de-regressão.html#cb72-21" tabindex="-1"></a>dados_filtrados <span class="ot">&lt;-</span> dados_finais <span class="sc">%&gt;%</span></span>
<span id="cb72-22"><a href="o-modelo-de-regressão.html#cb72-22" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb72-23"><a href="o-modelo-de-regressão.html#cb72-23" tabindex="-1"></a>  <span class="fu">inner_join</span>(municipios_segundo_turno, <span class="at">by =</span> <span class="st">&quot;NM_MUNICIPIO&quot;</span>)</span>
<span id="cb72-24"><a href="o-modelo-de-regressão.html#cb72-24" tabindex="-1"></a></span>
<span id="cb72-25"><a href="o-modelo-de-regressão.html#cb72-25" tabindex="-1"></a>dados_turno <span class="ot">&lt;-</span> dados_filtrados <span class="sc">%&gt;%</span></span>
<span id="cb72-26"><a href="o-modelo-de-regressão.html#cb72-26" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>NR_VOTAVEL <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">95</span>, <span class="dv">96</span>)) <span class="sc">%&gt;%</span> <span class="co"># nulos e brancos fora</span></span>
<span id="cb72-27"><a href="o-modelo-de-regressão.html#cb72-27" tabindex="-1"></a>   <span class="fu">pivot_wider</span>(</span>
<span id="cb72-28"><a href="o-modelo-de-regressão.html#cb72-28" tabindex="-1"></a>    <span class="at">id_cols =</span> <span class="fu">c</span>(DS_ELEICAO, NM_MUNICIPIO, NR_ZONA, NR_SECAO, NR_VOTAVEL),</span>
<span id="cb72-29"><a href="o-modelo-de-regressão.html#cb72-29" tabindex="-1"></a>    <span class="at">names_from =</span> NR_TURNO,</span>
<span id="cb72-30"><a href="o-modelo-de-regressão.html#cb72-30" tabindex="-1"></a>    <span class="at">values_from =</span> votos_nominais,</span>
<span id="cb72-31"><a href="o-modelo-de-regressão.html#cb72-31" tabindex="-1"></a>    <span class="at">names_prefix =</span> <span class="st">&quot;votos_turno_&quot;</span></span>
<span id="cb72-32"><a href="o-modelo-de-regressão.html#cb72-32" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb72-33"><a href="o-modelo-de-regressão.html#cb72-33" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">votos_1turno =</span> votos_turno_1,</span>
<span id="cb72-34"><a href="o-modelo-de-regressão.html#cb72-34" tabindex="-1"></a>         <span class="at">votos_2turno =</span> votos_turno_2)</span>
<span id="cb72-35"><a href="o-modelo-de-regressão.html#cb72-35" tabindex="-1"></a></span>
<span id="cb72-36"><a href="o-modelo-de-regressão.html#cb72-36" tabindex="-1"></a>dados_turno1 <span class="ot">&lt;-</span> dados_turno <span class="sc">%&gt;%</span></span>
<span id="cb72-37"><a href="o-modelo-de-regressão.html#cb72-37" tabindex="-1"></a>  <span class="fu">group_by</span>(NR_VOTAVEL, NM_MUNICIPIO) <span class="sc">%&gt;%</span></span>
<span id="cb72-38"><a href="o-modelo-de-regressão.html#cb72-38" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">voto_total_candidato_2t =</span> <span class="fu">sum</span>(votos_2turno, <span class="at">na.rm=</span>T),</span>
<span id="cb72-39"><a href="o-modelo-de-regressão.html#cb72-39" tabindex="-1"></a>         <span class="at">voto_total_candidato_1t =</span> <span class="fu">sum</span>(votos_1turno, <span class="at">na.rm=</span>T)) <span class="sc">%&gt;%</span></span>
<span id="cb72-40"><a href="o-modelo-de-regressão.html#cb72-40" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb72-41"><a href="o-modelo-de-regressão.html#cb72-41" tabindex="-1"></a>  <span class="fu">group_by</span>(NM_MUNICIPIO, NR_ZONA, NR_SECAO) <span class="sc">%&gt;%</span></span>
<span id="cb72-42"><a href="o-modelo-de-regressão.html#cb72-42" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">votos_validos_1t =</span> <span class="fu">sum</span>(votos_1turno),</span>
<span id="cb72-43"><a href="o-modelo-de-regressão.html#cb72-43" tabindex="-1"></a>         <span class="at">votos_validos_2t =</span> <span class="fu">sum</span>(votos_2turno, <span class="at">na.rm=</span>T)) <span class="sc">%&gt;%</span></span>
<span id="cb72-44"><a href="o-modelo-de-regressão.html#cb72-44" tabindex="-1"></a>  <span class="fu">filter</span>(voto_total_candidato_2t <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb72-45"><a href="o-modelo-de-regressão.html#cb72-45" tabindex="-1"></a>  <span class="fu">group_by</span>(NM_MUNICIPIO, NR_ZONA, NR_SECAO, NR_VOTAVEL) <span class="sc">%&gt;%</span></span>
<span id="cb72-46"><a href="o-modelo-de-regressão.html#cb72-46" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">perc_validos_1t =</span> votos_1turno<span class="sc">/</span>votos_validos_1t,</span>
<span id="cb72-47"><a href="o-modelo-de-regressão.html#cb72-47" tabindex="-1"></a>         <span class="at">perc_validos_2t =</span> votos_2turno<span class="sc">/</span>votos_validos_2t) <span class="sc">%&gt;%</span></span>
<span id="cb72-48"><a href="o-modelo-de-regressão.html#cb72-48" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb72-49"><a href="o-modelo-de-regressão.html#cb72-49" tabindex="-1"></a></span>
<span id="cb72-50"><a href="o-modelo-de-regressão.html#cb72-50" tabindex="-1"></a></span>
<span id="cb72-51"><a href="o-modelo-de-regressão.html#cb72-51" tabindex="-1"></a></span>
<span id="cb72-52"><a href="o-modelo-de-regressão.html#cb72-52" tabindex="-1"></a><span class="co"># salvando dados que iremos trabalhar em sala de aula efetivamente.</span></span>
<span id="cb72-53"><a href="o-modelo-de-regressão.html#cb72-53" tabindex="-1"></a><span class="fu">saveRDS</span>(dados_turno1, <span class="at">file=</span><span class="fu">here</span>(<span class="st">&quot;Dados//&quot;</span>, <span class="st">&quot;dados_turno1.rds&quot;</span>))</span></code></pre></div>
<p>O que constitui uma boa previsão? Tradicionalmente, empregamos a noção de Erro Quadrátco Médio (EQM) para quantificar boas previsões. Quanto menor o EQM, melhor uma previsão. Se o objetivo é, portanto, fazer previsões que minimizem o EQM, iremos apresertar e mostrar que a Função de Esperança Condicional (<em>CEF</em>, na sigla em inglês) é o melhor preditor global possível. Vamos dizer, em outras palavras, porque esse resultado é verdadeiramente incrível. A CEF é o melhor preditor possível dentre todos que existam ou possam vir a existir, entendendo melhor como ter o menor EQM. Por isso que a CEF é o ponto de partida de qualquer preditor que exista, seja uma regressão simples ou algoritmos de aprendizens de máquinas como “random forest” ou mesmo algorítimos de deep learning de redes neurais por traz dos recentes avanços na inteligência artificial.</p>
<blockquote>
<p>Mesmo os algorítmos mais avançados de inteleigência artificial, como os <strong>Large Language Models</strong>, que estão na base de ferramentas como ChatGPT, <em>não podem</em> ter desempenho melhor que a função de experança condicional, CEF, ao fazer uma previsão.</p>
</blockquote>
<p>Naturalmente, se esse é o caso, a próxima pergunta que todos nós iremos fazer é: por que não aprender apenas a usar a CEF, que é o melhor preditor possível, e ser feliz para sempre? Porque a natureza não nos diz qual é a CEF. Nós nunca sabemos qual a verdadeira função de esperança condicional. Então tentamos aproximar o mais bem possível a CEF, a partir de simplificações da realidade. Em particular, nosso curso pode ser pensado em torno das seguintes perguntas: como aproximar a CEF por meio de regressão linear (combinação lineares de preditores)? Quais as propridades dessa aproximação? Em que condições ela é uma boa aproximação e em que sentido (quantitativo e preciso) podemos falar de boa aproximação? Mais para o final do curso faremos a conexão entre a CEF, modelos preditivos e modelos causais.</p>
</div>
<div id="cef-e-voto" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> CEF e voto<a href="o-modelo-de-regressão.html#cef-e-voto" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="o-modelo-de-regressão.html#cb73-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb73-2"><a href="o-modelo-de-regressão.html#cb73-2" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb73-3"><a href="o-modelo-de-regressão.html#cb73-3" tabindex="-1"></a></span>
<span id="cb73-4"><a href="o-modelo-de-regressão.html#cb73-4" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> dados_turno1 <span class="sc">%&gt;%</span></span>
<span id="cb73-5"><a href="o-modelo-de-regressão.html#cb73-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>perc_validos_1t , <span class="at">y =</span> perc_validos_2t )) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">22</span>) <span class="sc">+</span></span>
<span id="cb73-6"><a href="o-modelo-de-regressão.html#cb73-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb73-7"><a href="o-modelo-de-regressão.html#cb73-7" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb73-8"><a href="o-modelo-de-regressão.html#cb73-8" tabindex="-1"></a></span>
<span id="cb73-9"><a href="o-modelo-de-regressão.html#cb73-9" tabindex="-1"></a><span class="fu">print</span>(p1)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="bookdownproj_files/figure-html/voto_turnos_todos_municipios%20cap5-1.png" alt="voto" width="900" />
<p class="caption">
(#fig:voto_turnos_todos_municipios cap5)voto
</p>
</div>
<p>O gráfico agrupando todos os munícipios de São Paulo sem distinção mostra uma correlação positiva, mas muita variabilidade. Vamos ver por município.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="o-modelo-de-regressão.html#cb74-1" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> dados_turno1 <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="o-modelo-de-regressão.html#cb74-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>perc_validos_1t , <span class="at">y =</span> perc_validos_2t )) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">22</span>) <span class="sc">+</span></span>
<span id="cb74-3"><a href="o-modelo-de-regressão.html#cb74-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> NM_MUNICIPIO) <span class="sc">+</span></span>
<span id="cb74-4"><a href="o-modelo-de-regressão.html#cb74-4" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span> </span>
<span id="cb74-5"><a href="o-modelo-de-regressão.html#cb74-5" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb74-6"><a href="o-modelo-de-regressão.html#cb74-6" tabindex="-1"></a></span>
<span id="cb74-7"><a href="o-modelo-de-regressão.html#cb74-7" tabindex="-1"></a><span class="fu">print</span>(p2)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="bookdownproj_files/figure-html/voto_turnos_por_municipios-1.png" alt="voto_por_municipio" width="900" />
<p class="caption">
(#fig:voto_turnos_por_municipios)voto_por_municipio
</p>
</div>
<p>Os gráficos fazem mais sentido e a variabilidade diminuiu no geral, mas alguns municípios estão com padrões estranhos. Vamos colorir os pontos por candidato?</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="o-modelo-de-regressão.html#cb75-1" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> dados_turno1 <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="o-modelo-de-regressão.html#cb75-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>perc_validos_1t , <span class="at">y =</span> perc_validos_2t, <span class="at">colour =</span> NR_VOTAVEL)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">22</span>) <span class="sc">+</span></span>
<span id="cb75-3"><a href="o-modelo-de-regressão.html#cb75-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> NM_MUNICIPIO) <span class="sc">+</span></span>
<span id="cb75-4"><a href="o-modelo-de-regressão.html#cb75-4" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span> </span>
<span id="cb75-5"><a href="o-modelo-de-regressão.html#cb75-5" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb75-6"><a href="o-modelo-de-regressão.html#cb75-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;none&quot;</span>)</span>
<span id="cb75-7"><a href="o-modelo-de-regressão.html#cb75-7" tabindex="-1"></a></span>
<span id="cb75-8"><a href="o-modelo-de-regressão.html#cb75-8" tabindex="-1"></a><span class="fu">print</span>(p3)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="bookdownproj_files/figure-html/voto_turnos_por_municipios_candidatos-1.png" alt="voto_por_municipio" width="900" />
<p class="caption">
(#fig:voto_turnos_por_municipios_candidatos)voto_por_municipio
</p>
</div>
<p>Municípios como Diadema, Sorocaba, Franca e Taubaté, que não estavam fazendo muito sentido, agora passaram a fazer.</p>
<p>E o que é a Esperana Condicional?
Qual o valor esperado do <span class="math inline">\(Y\)</span> para um davo valor de <span class="math inline">\(X\)</span>. No gráfico, é dado pela linha vermelha.</p>
</div>
<div id="algumas-propriedades-da-cef" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Algumas Propriedades da CEF<a href="o-modelo-de-regressão.html#algumas-propriedades-da-cef" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A CEF é simplesmente uma função de <span class="math inline">\(X_i\)</span> que resulta na esperança condficional, ou seja <span class="math inline">\(\mathbb{E}[Y_i|X_i]\)</span>. É como se eu escrevesse <span class="math inline">\(f(X_i) = \mathbb{E}[Y_i|X_i]\)</span>.</p>
<p>Como <span class="math inline">\(X_i\)</span> pode ser pensado como aleatório, então a CEF também é aleatória.</p>
<p>Nós podemos descrever os dados da seguinte forma: <span class="math inline">\(Y_i = \mathbb{E}[Y_i|X_i] + e_i\)</span>. Ou seja, a Esperança condicional mais um termo de erro. Nós veremos que é possível mostrar que <span class="math inline">\(\mathbb{E}[e_i|X_i] = 0\)</span>, ou seja, independência na média.</p>
<div id="cef-é-a-melhor-aproximação-aos-dados" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> CEF é a melhor aproximação aos dados<a href="#cef-%C3%A9-a-melhor-aproxima%C3%A7%C3%A3o-aos-dados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponha que estamos interessados em achar a melhor função de <span class="math inline">\(X\)</span>, <span class="math inline">\(m(x)\)</span> que aproximada os dados <span class="math inline">\(Y\)</span>. Qual seria essa função? Se nós utilizamos o EQM para computar quão bem estamos aproximando os dados, então:</p>
<p><span class="math inline">\((Y_i - m(X_i))^2 = ((Y_i - \mathbb{E}[Y_i|X_i]) + (\mathbb{E}[Y_i|X_i] - m(X_i)))^2\)</span></p>
<p><span class="math inline">\((Y_i - m(X_i))^2 = (Y_i - \mathbb{E}[Y_i|X_i])^2 + 2(Y_i - \mathbb{E}[Y_i|X_i])(\mathbb{E}[Y_i|X_i] - m(X_i) + (\mathbb{E}[Y_i|X_i] - m(X_i))^2\)</span></p>
<p>Nós queremos minimizar a esperança do erro quadrático, isto é, achar <span class="math inline">\(m(X_i)\)</span> que torna o EQM mínimo. Logo, sabemos que qulquer que seja o <span class="math inline">\(m(X_i)\)</span> que minimiza o EQM, não impacta o primeiro termo da equação acima, de forma que podemos desconsiderá-lo. <span class="math inline">\(Y_i - \mathbb{E}[Y_i|X_i]\)</span> é <span class="math inline">\(e_i\)</span>. Como a esperança de <span class="math inline">\(e_i\)</span> é zero, então todo o termo é zero. De forma que só sobra a esperança do último termo. E o melhor que se pode fazer é zerar o termo, ou seja, <span class="math inline">\(m(X_i) = \mathbb{E}[Y_i|X_i]\)</span>.</p>
</div>
</div>
<div id="regressão-linear" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Regressão Linear<a href="#regress%C3%A3o-linear" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Como podemos ver nos gráficos, a esperança condicional é em geral não-linear. A ideia da regressão linear é aproximar a CEF por meio de uma reta.</p>
<p>Vamos plotar a reta de regressão linear nos gráficos, juntamente com a CEF.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="o-modelo-de-regressão.html#cb76-1" tabindex="-1"></a><span class="co"># Criar o gráfico</span></span>
<span id="cb76-2"><a href="o-modelo-de-regressão.html#cb76-2" tabindex="-1"></a>grafico_cef_reg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb76-3"><a href="o-modelo-de-regressão.html#cb76-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dados_binned, <span class="fu">aes</span>(<span class="at">x =</span> perc_validos_1t, <span class="at">y =</span> perc_validos_2t), </span>
<span id="cb76-4"><a href="o-modelo-de-regressão.html#cb76-4" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-5"><a href="o-modelo-de-regressão.html#cb76-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> cef_data, <span class="fu">aes</span>(<span class="at">x =</span> bin_center, <span class="at">y =</span> perc_validos_2t_mean), </span>
<span id="cb76-6"><a href="o-modelo-de-regressão.html#cb76-6" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb76-7"><a href="o-modelo-de-regressão.html#cb76-7" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> cef_data, <span class="fu">aes</span>(<span class="at">x =</span> bin_center, <span class="at">y =</span> perc_validos_2t_mean), </span>
<span id="cb76-8"><a href="o-modelo-de-regressão.html#cb76-8" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-9"><a href="o-modelo-de-regressão.html#cb76-9" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> dados_binned, <span class="fu">aes</span>(<span class="at">x =</span> perc_validos_1t, <span class="at">y =</span> perc_validos_2t), <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>,<span class="at">linewidth=</span><span class="dv">1</span>, <span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb76-10"><a href="o-modelo-de-regressão.html#cb76-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>NM_MUNICIPIO) <span class="sc">+</span></span>
<span id="cb76-11"><a href="o-modelo-de-regressão.html#cb76-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;CEF e Reta de Regressão Linear&quot;</span>,</span>
<span id="cb76-12"><a href="o-modelo-de-regressão.html#cb76-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Percentual de Votos Válidos no 1º Turno&quot;</span>,</span>
<span id="cb76-13"><a href="o-modelo-de-regressão.html#cb76-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Percentual Médio de Votos Válidos no 2º Turno&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-14"><a href="o-modelo-de-regressão.html#cb76-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb76-15"><a href="o-modelo-de-regressão.html#cb76-15" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb76-16"><a href="o-modelo-de-regressão.html#cb76-16" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> scales<span class="sc">::</span>percent) </span>
<span id="cb76-17"><a href="o-modelo-de-regressão.html#cb76-17" tabindex="-1"></a></span>
<span id="cb76-18"><a href="o-modelo-de-regressão.html#cb76-18" tabindex="-1"></a><span class="fu">print</span>(grafico_cef_reg)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="bookdownproj_files/figure-html/CEF_voto_turnos_regressao-1.png" alt="voto_por_municipio" width="900" />
<p class="caption">
(#fig:CEF_voto_turnos_regressao)voto_por_municipio
</p>
</div>
</div>
<div id="logaritmos" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Logaritmos<a href="o-modelo-de-regressão.html#logaritmos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>É muito comum a utilização de logaritmos em regressões, de modo que vale uma digresssão sobre a correta interpretação de logaritmos. A primeira razão é que a diferença de logaritmos é aproximadamente igual à diferença entre porcentagens. Vamos ilustrar isso por meio de um exemplo, e então mostaremos matematicamente que isso sempre é o caso.</p>
<div id="logartimos-como-diferença-de-porcentagens" class="section level3 hasAnchor" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Logartimos como diferença de porcentagens<a href="#logartimos-como-diferen%C3%A7a-de-porcentagens" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De acodo com dados da PNADc de 2017, quarto trimstre, o salário por hora dos homens é em média <span class="math inline">\(14.72\)</span> reais, e o das mulheres <span class="math inline">\(12.57\)</span> reais. A diferença percentual no salário é, portanto, <span class="math inline">\(100*(14.72 - 12.57)/12.57\)</span> ou <span class="math inline">\(17,1%\)</span>. Se em vez de calcular a diferença percentual, usar a aproximação <span class="math inline">\(log(14.72) - log(12.57) = 0.1578941\)</span> ou 15,8%, tenho um valor próximo do verdadeiro valor de 17,1%.</p>
<p>O caso geral pode ser visto do seguinte modo. Sejam dois números positivos <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span>, com <span class="math inline">\(a &gt; b\)</span>. A diferença percentual <span class="math inline">\(p\)</span> entre <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> é dada por:</p>
<p><span class="math display">\[
100*(a - b)/b = p
\]</span>
Que é o mesmo que:</p>
<p><span class="math display">\[
a/b = 1 + p/100
\]</span>
Se passarmos o logaritmo natural de ambos os lados, temos:</p>
<p><span class="math display">\[
log(a/b) = log(1 + p/100)
\]</span>
<span class="math display">\[
log(a) - log(b) = log(1 + p/100)
\]</span>
Iremos usar a aproximação <span class="math inline">\(log( 1 + x) \approx x\)</span> para <span class="math inline">\(x\)</span> pequeno. Logo:</p>
<p><span class="math display">\[
log(a) - log(b) \approx p/100
\]</span>
Numericamente, como o erro dessa aproximação varia para diferentes valores de <span class="math inline">\(p\)</span>?</p>
<p>Exercício em sala: Vamos fazer uma simulação para verificar como o erro da aproximação funciona. Ou seja, vamos variar a diferença percentual entre dois números <span class="math inline">\(a\)</span> e <span class="math inline">\(b\)</span> e calcular o erro de aproximação pela fórmula com logaritmo.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="o-modelo-de-regressão.html#cb77-1" tabindex="-1"></a>dif_perc <span class="ot">&lt;-</span> <span class="cf">function</span>(a,b){</span>
<span id="cb77-2"><a href="o-modelo-de-regressão.html#cb77-2" tabindex="-1"></a>  <span class="fu">stopifnot</span>(a <span class="sc">&gt;</span> b)</span>
<span id="cb77-3"><a href="o-modelo-de-regressão.html#cb77-3" tabindex="-1"></a>  <span class="dv">100</span><span class="sc">*</span>(a <span class="sc">-</span> b)<span class="sc">/</span>b </span>
<span id="cb77-4"><a href="o-modelo-de-regressão.html#cb77-4" tabindex="-1"></a>}</span>
<span id="cb77-5"><a href="o-modelo-de-regressão.html#cb77-5" tabindex="-1"></a></span>
<span id="cb77-6"><a href="o-modelo-de-regressão.html#cb77-6" tabindex="-1"></a>aprox_dif_perc <span class="ot">&lt;-</span> <span class="cf">function</span>(a,b){</span>
<span id="cb77-7"><a href="o-modelo-de-regressão.html#cb77-7" tabindex="-1"></a>  <span class="fu">stopifnot</span>(a <span class="sc">&gt;</span> b)</span>
<span id="cb77-8"><a href="o-modelo-de-regressão.html#cb77-8" tabindex="-1"></a>  <span class="dv">100</span><span class="sc">*</span>(<span class="fu">log</span>(a) <span class="sc">-</span> <span class="fu">log</span>(b))</span>
<span id="cb77-9"><a href="o-modelo-de-regressão.html#cb77-9" tabindex="-1"></a>}</span>
<span id="cb77-10"><a href="o-modelo-de-regressão.html#cb77-10" tabindex="-1"></a></span>
<span id="cb77-11"><a href="o-modelo-de-regressão.html#cb77-11" tabindex="-1"></a>erro_aprox_perc <span class="ot">&lt;-</span> <span class="cf">function</span>(a,b) {</span>
<span id="cb77-12"><a href="o-modelo-de-regressão.html#cb77-12" tabindex="-1"></a>  <span class="fu">dif_perc</span>(a,b) <span class="sc">-</span> <span class="fu">aprox_dif_perc</span>(a,b)</span>
<span id="cb77-13"><a href="o-modelo-de-regressão.html#cb77-13" tabindex="-1"></a>}</span>
<span id="cb77-14"><a href="o-modelo-de-regressão.html#cb77-14" tabindex="-1"></a></span>
<span id="cb77-15"><a href="o-modelo-de-regressão.html#cb77-15" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb77-16"><a href="o-modelo-de-regressão.html#cb77-16" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">100.1</span>, <span class="dv">120</span>, <span class="at">by=</span>.<span class="dv">1</span>)</span>
<span id="cb77-17"><a href="o-modelo-de-regressão.html#cb77-17" tabindex="-1"></a>vec_erro <span class="ot">&lt;-</span> <span class="fu">numeric</span>()</span>
<span id="cb77-18"><a href="o-modelo-de-regressão.html#cb77-18" tabindex="-1"></a>true_p <span class="ot">&lt;-</span> <span class="fu">numeric</span>()</span>
<span id="cb77-19"><a href="o-modelo-de-regressão.html#cb77-19" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(a)) {</span>
<span id="cb77-20"><a href="o-modelo-de-regressão.html#cb77-20" tabindex="-1"></a>  vec_erro[i] <span class="ot">&lt;-</span> <span class="fu">erro_aprox_perc</span>(a[i],b)</span>
<span id="cb77-21"><a href="o-modelo-de-regressão.html#cb77-21" tabindex="-1"></a>  true_p[i] <span class="ot">&lt;-</span> <span class="fu">dif_perc</span>(a[i],b)</span>
<span id="cb77-22"><a href="o-modelo-de-regressão.html#cb77-22" tabindex="-1"></a>}</span>
<span id="cb77-23"><a href="o-modelo-de-regressão.html#cb77-23" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">erro =</span> vec_erro, <span class="at">p =</span> true_p )</span>
<span id="cb77-24"><a href="o-modelo-de-regressão.html#cb77-24" tabindex="-1"></a></span>
<span id="cb77-25"><a href="o-modelo-de-regressão.html#cb77-25" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb77-26"><a href="o-modelo-de-regressão.html#cb77-26" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb77-27"><a href="o-modelo-de-regressão.html#cb77-27" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb77-28"><a href="o-modelo-de-regressão.html#cb77-28" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>p, <span class="at">y=</span>erro)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb77-29"><a href="o-modelo-de-regressão.html#cb77-29" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> .<span class="dv">1</span>, <span class="at">colour=</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb77-30"><a href="o-modelo-de-regressão.html#cb77-30" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Diferença Percentual Real&quot;</span>, </span>
<span id="cb77-31"><a href="o-modelo-de-regressão.html#cb77-31" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Erro de Aproximação (p.p.)&quot;</span>,</span>
<span id="cb77-32"><a href="o-modelo-de-regressão.html#cb77-32" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Erro na Aproximação da Dif Per&quot;</span>) <span class="sc">+</span></span>
<span id="cb77-33"><a href="o-modelo-de-regressão.html#cb77-33" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-6-1.png" width="900" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="o-modelo-de-regressão.html#cb78-1" tabindex="-1"></a><span class="co"># Verificação do intervalo onde o erro é menor que 0.1 pp</span></span>
<span id="cb78-2"><a href="o-modelo-de-regressão.html#cb78-2" tabindex="-1"></a>df<span class="sc">$</span>within_tolerance <span class="ot">&lt;-</span> <span class="fu">abs</span>(df<span class="sc">$</span>erro) <span class="sc">&lt;</span> <span class="fl">0.1</span></span>
<span id="cb78-3"><a href="o-modelo-de-regressão.html#cb78-3" tabindex="-1"></a>max_p_within_tolerance <span class="ot">&lt;-</span> <span class="fu">max</span>(df<span class="sc">$</span>p[df<span class="sc">$</span>within_tolerance])</span>
<span id="cb78-4"><a href="o-modelo-de-regressão.html#cb78-4" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Máximo p com erro &lt; 0.1 pp:&quot;</span>, <span class="fu">round</span>(max_p_within_tolerance, <span class="dv">2</span>)))</span></code></pre></div>
<pre><code>## [1] &quot;Máximo p com erro &lt; 0.1 pp: 4.5&quot;</code></pre>
<p>A segunda razão é que se aplicarmos essa lógica para médias, estamos aproximando a diferença percentual na média geométrica.</p>
</div>
<div id="logaritmos-e-média-geométrica" class="section level3 hasAnchor" number="5.6.2">
<h3><span class="header-section-number">5.6.2</span> Logaritmos e média geométrica<a href="#logaritmos-e-m%C3%A9dia-geom%C3%A9trica" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A média geométrica de um conjunto de observações <span class="math inline">\((x_1, x_2, \cdots, x_n)\)</span> é dada por: <span class="math inline">\(MG = \sqrt[n]{(x_1 \cdot x_2 \cdot x_n)}\)</span>.</p>
<p>Se considerarmos variáveis aleatórias, <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>, ambas positivas, e suas respectivas transformações com logaritmo, <span class="math inline">\(log(X)\)</span> e <span class="math inline">\(log(Y)\)</span>, definimos a média geométrica <span class="math inline">\(\theta_x = \exp(\mathbb{E}[log(X)])\)</span> e <span class="math inline">\(\theta_y = \exp(\mathbb{E}[log(Y)])\)</span> e a diferença percentual como:</p>
<p><span class="math inline">\(p = 100\frac{(\theta_y - \theta_x)}{\theta_x}\)</span></p>
<p>A diferença na esperança da transformações do log é:</p>
<p><span class="math inline">\(100(\mathbb{E}[log Y] - \mathbb{E}[log X]) = 100 (log \theta_y - log \theta_x) \approx p\)</span></p>
<p>Em paavras: A diferença na média de variáveis transformadas (pelo log) é aproximadamente a diferença percentual nas médias geométricas. Isso é relevante por causa do seguinte.
Suponha que temos o logaritmo do salário de homens e mulheres:</p>
<p><span class="math inline">\(\mathbb{E}[Y|homem] =\mu_1\)</span>
<span class="math inline">\(\mathbb{E}[Y|mulher] =\mu_2\)</span></p>
<p>Podemos dizer que a diferença <span class="math inline">\(\mu_2 - \mu_1\)</span> é aproximadamente a diferença percentual na média geométrica.</p>
</div>
</div>
<div id="prevendo-a-partir-da-esperança-condicional" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Prevendo a partir da esperança condicional<a href="#prevendo-a-partir-da-esperan%C3%A7a-condicional" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>No gráfico abaixo, as esperanças condicionais para os dois valores de <span class="math inline">\(X\)</span> são dadas pelos triângulos vermelhos. Como vemos, há uma grande variabilidade nos dados de salário em torno da esperança condicional. Isso significa que se só tenho a variável gênero, prever <span class="math inline">\(Y\)</span> a partir da esperança condicional <span class="math inline">\(\mathbb{E}[Y|X]\)</span> resulta em um erro grande.</p>
<p>De fato, o erro que cometemos pode ser calculado por meio do <em>Erro Quadrático Médio</em>, que é definido como a soma dos erros ao quadrado (para não cancelar). No R, isso pode ser calculado como:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="o-modelo-de-regressão.html#cb80-1" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb80-2"><a href="o-modelo-de-regressão.html#cb80-2" tabindex="-1"></a><span class="co"># df_erro &lt;- df %&gt;%</span></span>
<span id="cb80-3"><a href="o-modelo-de-regressão.html#cb80-3" tabindex="-1"></a><span class="co">#   group_by(genero) %&gt;%</span></span>
<span id="cb80-4"><a href="o-modelo-de-regressão.html#cb80-4" tabindex="-1"></a><span class="co">#   mutate(cond_exp = mean(log_salario)) %&gt;%</span></span>
<span id="cb80-5"><a href="o-modelo-de-regressão.html#cb80-5" tabindex="-1"></a><span class="co">#   ungroup() %&gt;%</span></span>
<span id="cb80-6"><a href="o-modelo-de-regressão.html#cb80-6" tabindex="-1"></a><span class="co">#   mutate(erro = log_salario - cond_exp)</span></span>
<span id="cb80-7"><a href="o-modelo-de-regressão.html#cb80-7" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb80-8"><a href="o-modelo-de-regressão.html#cb80-8" tabindex="-1"></a><span class="co"># df_erro %&gt;%</span></span>
<span id="cb80-9"><a href="o-modelo-de-regressão.html#cb80-9" tabindex="-1"></a><span class="co">#   select(log_salario, genero, cond_exp, erro) %&gt;%</span></span>
<span id="cb80-10"><a href="o-modelo-de-regressão.html#cb80-10" tabindex="-1"></a><span class="co">#   head() %&gt;%</span></span>
<span id="cb80-11"><a href="o-modelo-de-regressão.html#cb80-11" tabindex="-1"></a><span class="co">#   kable()</span></span>
<span id="cb80-12"><a href="o-modelo-de-regressão.html#cb80-12" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb80-13"><a href="o-modelo-de-regressão.html#cb80-13" tabindex="-1"></a><span class="co"># df_erro %&gt;%</span></span>
<span id="cb80-14"><a href="o-modelo-de-regressão.html#cb80-14" tabindex="-1"></a><span class="co">#   summarise(eq = round(sum(erro),4),</span></span>
<span id="cb80-15"><a href="o-modelo-de-regressão.html#cb80-15" tabindex="-1"></a><span class="co">#          eqm =  sum(erro^2)) %&gt;%</span></span>
<span id="cb80-16"><a href="o-modelo-de-regressão.html#cb80-16" tabindex="-1"></a><span class="co">#   kable()</span></span></code></pre></div>
<p>Como iremos mostrar depois, não existe nenhuma outra forma melhor de prever <span class="math inline">\(Y\)</span>, se só tivermos informação de <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span>. Ou seja, esse é o menor erro quadrático médio possível. Claro que, com mais variávels, podemos condicionais em mais informação e melhorar a previsão. Por exemplo, se temos a variável raça, além de gênero, podemos condicionar nas duas variáveis.</p>
<p>Vemos que o EQM diminuiu ao condicionar em mais variáveis. Para reforçar, até aqui estamos falando da população. Embora no exemplo tenhamos dados da PNAD, que é uma amostra, e em teoria deveríamos trabalhar com o censo, estou simplificando e assumindo que a PNAD representa a população. Fazendo essa suposição, o erro que é cometido pela esperança condicional para prever <span class="math inline">\(Y\)</span> é o menor erro (quantificado pelo EQM) possível (iremos demonstrar isso no próximo capítulo).</p>
</div>
<div id="preditores-lineares" class="section level2 hasAnchor" number="5.8">
<h2><span class="header-section-number">5.8</span> Preditores lineares<a href="o-modelo-de-regressão.html#preditores-lineares" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Como vimos, uma boa aproximação para a CEF é um preditor linear. Se temos um preditor <span class="math inline">\(x\)</span> e queremos usar esse preditor para prever <span class="math inline">\(y\)</span>, o modelo linear simples pode ser escrito da seguinte forma:</p>
<p><span class="math display">\[
\hat{y_i} = \alpha + \beta x_i
\]</span>
Vejam que eu usei <span class="math inline">\(x_i\)</span>, mas não <span class="math inline">\(y_i\)</span>. Em vez disso, utilizei <span class="math inline">\(\hat{y}_i\)</span>. Este último valor é a minha previsão do <span class="math inline">\(y\)</span> dado o valor do meu preditor <span class="math inline">\(x\)</span> para cada observação <span class="math inline">\(i\)</span>. Vejam que, uma vez que nós saibamos os valores de <span class="math inline">\(\alpha\)</span> e <span class="math inline">\(\beta\)</span>, temos efetivamente uma reta (linear) que relaciona <span class="math inline">\(x_i\)</span> e <span class="math inline">\(\hat{y}_i\)</span>. Um critério para tal é minimizar a diferença, para cada observação, entre <span class="math inline">\(y\)</span> e <span class="math inline">\(\hat{y}\)</span>, isto é:</p>
<p><span class="math display">\[
\min_{\mathbf{\alpha, \beta}}\sum_i^n (y_i - \hat{y}_i)^2
\]</span>
A notação fica mais simples com a esperança matemática:
<span class="math display">\[
\min_{\mathbf{\alpha, \beta}} \mathbb{E}[(Y - \hat{Y})^2]
\]</span>
Por essa razão, chamamos de: preditor linear de erro quadrático médio mínimo.</p>
<p>Por hora, basta saber que se minimizarmos a soma (ou a esperança) obteremos os valores de <span class="math inline">\(\alpha\)</span> e <span class="math inline">\(\beta\)</span>. Quando falamos de uma amostra (em vez da população), iremos indicar esses valores por <span class="math inline">\(\hat{\alpha}\)</span> e <span class="math inline">\(\hat{\beta}\)</span>.</p>
<p>Essa previsão, por mais que nós estejamos tentando minimizar o erro entre o valor do <span class="math inline">\(y\)</span> e previsto <span class="math inline">\(\hat{y}\)</span>, em geral não será perfeito. Assim, para cada previsão <span class="math inline">\(\hat{y}_i\)</span> cometo um erro <span class="math inline">\(\epsilon_i\)</span> que é a diferença entre o observado <span class="math inline">\(y\)</span> e o precisto <span class="math inline">\(\hat{y}\)</span>, ou seja:</p>
<p><span class="math display">\[
\epsilon_i = y_i - \hat{y}_i
\]</span></p>
<p>Se eu substituir <span class="math inline">\(\hat{y}_i\)</span> pos sua equação, temos:</p>
<p><span class="math display">\[
\epsilon_i = y_i - \alpha - \beta x_i
\]</span></p>
<p>Rearranjando:
<span class="math display">\[
y_i = \alpha + \beta x_i + \epsilon_i
\]</span>
Esse é chamado de modelo de regressão linear. Em resumo, o preditor linear é <span class="math inline">\(\hat{y}_i = \alpha + \beta x_i\)</span> e o modelo de regressão lienar é <span class="math inline">\(y_i = \alpha + \beta x_i + \epsilon_i\)</span>. No primeiro caso, tenho uma previsão que é diferente do observado. No segundo caso, acoplo a previsão ao erro e obtenho exatamente o observado.</p>
<p>Vale notar que minimizar a soma dos quadrados dos resíduos é o mesmo que minimizar a a raiz quadrada dessa soma dividida por <span class="math inline">\(n\)</span>, ou seja:</p>
<p><span class="math display">\[
\min_{\mathbf{\alpha, \beta}}\sum_i^n (y_i - \hat{y}_i)^2 = \min_{\mathbf{\alpha, \beta}} \sqrt{\frac{1}{n}\sum_i^n (y_i - \hat{y}_i)^2}
\]</span></p>
<p>Essa soma com a raiz quadrada é chamada de erro raiz-quadrático médio (Root-Mean-Squared-Error ou RMSE em inglês). Vamos calcular no R um modelo de regressão linear e depois o RMSE de nossos dados.</p>
<p>Para rodar uma regressão no R, usamos a função lm(). Ela recebe a fórmula na forma <span class="math inline">\(y \sim x\)</span>, em que <span class="math inline">\(y\)</span> é a variável resposta e <span class="math inline">\(x\)</span> o preditor. Não é preciso escrever os coeficientes <span class="math inline">\(\alpha\)</span> e <span class="math inline">\(\beta\)</span>. O R vai calcular eles pra gente e teremos estimativas amostrais <span class="math inline">\(\hat{\alpha}\)</span> e <span class="math inline">\(\hat{\beta}\)</span>.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="o-modelo-de-regressão.html#cb81-1" tabindex="-1"></a><span class="co"># vamos ficar só com o candidato mais votado</span></span>
<span id="cb81-2"><a href="o-modelo-de-regressão.html#cb81-2" tabindex="-1"></a>dados_filtrados <span class="ot">&lt;-</span> dados_turno1 <span class="sc">%&gt;%</span></span>
<span id="cb81-3"><a href="o-modelo-de-regressão.html#cb81-3" tabindex="-1"></a>  <span class="fu">group_by</span>(NM_MUNICIPIO) <span class="sc">%&gt;%</span></span>
<span id="cb81-4"><a href="o-modelo-de-regressão.html#cb81-4" tabindex="-1"></a>  <span class="co"># calcula o valor máximo de votos no 2º turno por município</span></span>
<span id="cb81-5"><a href="o-modelo-de-regressão.html#cb81-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">max_votos_2t =</span> <span class="fu">max</span>(voto_total_candidato_2t, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb81-6"><a href="o-modelo-de-regressão.html#cb81-6" tabindex="-1"></a>  <span class="co"># mantém apenas os candidatos que atingiram esse valor</span></span>
<span id="cb81-7"><a href="o-modelo-de-regressão.html#cb81-7" tabindex="-1"></a>  <span class="fu">filter</span>(voto_total_candidato_2t <span class="sc">==</span> max_votos_2t) <span class="sc">%&gt;%</span></span>
<span id="cb81-8"><a href="o-modelo-de-regressão.html#cb81-8" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb81-9"><a href="o-modelo-de-regressão.html#cb81-9" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>max_votos_2t)</span>
<span id="cb81-10"><a href="o-modelo-de-regressão.html#cb81-10" tabindex="-1"></a>  </span>
<span id="cb81-11"><a href="o-modelo-de-regressão.html#cb81-11" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(perc_validos_2t <span class="sc">~</span> perc_validos_1t, <span class="at">data =</span> dados_filtrados)</span>
<span id="cb81-12"><a href="o-modelo-de-regressão.html#cb81-12" tabindex="-1"></a>reg</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = perc_validos_2t ~ perc_validos_1t, data = dados_filtrados)
## 
## Coefficients:
##     (Intercept)  perc_validos_1t  
##          0.3624           0.6597</code></pre>
<p>O resultado do modelo mostra que o intecepto (<span class="math inline">\(\hat{\alpha}\)</span>) é <span class="math inline">\(0.3624\)</span> e a inclinação (o <span class="math inline">\(\hat{\beta}\)</span>) é 0.6597. O R não reporta o nome dos coeficientes <span class="math inline">\(\hat{\alpha}\)</span> ou <span class="math inline">\(\hat{\beta}\)</span> mas intercepto para o caso do <span class="math inline">\(\hat{\alpha}\)</span> e o nome do preditor para o caso do <span class="math inline">\(\hat{\beta}\)</span>. E interpretamos esse resultado do seguinte modo: quando o preditor é zero, ou seja, quando o voto no primeiro turno do vencedor da eleição é zero naquela seção eleitoral, a previsão do modelo é que no segundo turno o candidato mais votado tem 36,24% dos votos na seção. E cada ponto percentual de voto na seção se traduz em <span class="math inline">\(.01*0.6597 = 0.006597\)</span> pontos percentuais adicionais, ou seja, 1 ponto pecentual de voto na seção eleitoral se traduz em 0,6597 pontos percentuais. Em outras palavras, o candidato vencedor que teve 1% de voto numa seção eleitoral deve ter (é a previsão do modelo) <span class="math inline">\(0.3624 + .01*0.6597 = 0.368997\)</span> ou aproximadamente 37% dos votos na seção. Similarmente, se esse candidato teve 10% dos votos naquela seção no primeiro turno, então a previsão é que tenha: <span class="math inline">\(0.3624 + .1*0.6597 = 0.42837\)</span> ou aproximadamente 43% dos votos.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="o-modelo-de-regressão.html#cb83-1" tabindex="-1"></a><span class="co"># vamos ficar só com o candidato mais votado</span></span>
<span id="cb83-2"><a href="o-modelo-de-regressão.html#cb83-2" tabindex="-1"></a>dados_filtrados <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="o-modelo-de-regressão.html#cb83-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span>perc_validos_2t, <span class="at">x =</span> perc_validos_1t)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">0.3624</span>, <span class="at">slope =</span> <span class="fl">0.6597</span>, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span> ) <span class="sc">+</span></span>
<span id="cb83-4"><a href="o-modelo-de-regressão.html#cb83-4" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">label=</span><span class="st">&quot;intercepto&quot;</span>, <span class="at">x=</span>.<span class="dv">05</span>, <span class="at">y=</span> .<span class="dv">33</span>, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="bookdownproj_files/figure-html/reg_reta_cap5-1.png" alt="voto_por_municipio" width="900" />
<p class="caption">
(#fig:reg_reta_cap5)voto_por_municipio
</p>
</div>
<p>E vamos obter o RMSE. Para isso, usaremos a função resid():</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="o-modelo-de-regressão.html#cb84-1" tabindex="-1"></a><span class="co"># vamos ficar só com o candidato mais votado</span></span>
<span id="cb84-2"><a href="o-modelo-de-regressão.html#cb84-2" tabindex="-1"></a>residuos <span class="ot">&lt;-</span> <span class="fu">resid</span>(reg)</span>
<span id="cb84-3"><a href="o-modelo-de-regressão.html#cb84-3" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(residuos<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1] 0.08419337</code></pre>
<p>Esse número implica que em média cometemos um erro (“resíduo médio”) de .08 pontos percentuais. Ou seja, em média nosso modelo faz previsões diferentes do observado da ordem de .08 pontos percentuais.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>A maior parte do curso será dedicadas a modelos preditivos, e apenas pontualmente falaremos de modelos causais<a href="o-modelo-de-regressão.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introdução-à-simulação.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cef-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/mgaldino/book-regression/edit/main/05-intro_reg.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.com/mgaldino/book-regression/blob/main/05-intro_reg.Rmd",
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
